language: go
sudo: false
go:
  - 1.9.x
env:
  global:
    - DATABASE_USER=postgres
    - DATABASE_NAME=worrywort_test
    - DATABASE_HOST=localhost
    - PGPORT=5432
before_install:
  - wget https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -O $HOME/gopath/bin/dep
  - chmod u+x $HOME/gopath/bin/dep
  - wget https://github.com/golang-migrate/migrate/releases/download/v3.2.0/migrate.linux-amd64.tar.gz -O $HOME/migrate.linux-amd64.tar.gz
  - tar -zxvf $HOME/migrate.linux-amd64.tar.gz -C $HOME/gopath/bin/
  - go get -t -v ./...
before_script:
  - go vet ./...
  - createdb -h localhost -U postgres worrywort_test -O postgres
  - migrate.linux-amd64 -source file://./_migrations -database postgres://postgres@localhost:5432/worrywort_test?sslmode=disable up
install:
  - dep ensure
#   # Add Godeps dependencies to GOPATH and PATH
#   - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
#   - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic
  - dep status

after_success:
  - bash <(curl -s https://codecov.io/bash)

# Instead of manual setup and build, consider using docker-compose just like for dev
# http://elliot.land/post/using-docker-compose-on-travis-ci
services:
  - postgresql
addons:
  postgresql: "9.6"
