language: go
sudo: false
go:
  - 1.9.x
before_install:
  - wget https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -O $HOME/gopath/bin/dep
before_script:
  - go vet ./...
install:
  - dep ensure
#   # Add Godeps dependencies to GOPATH and PATH
#   - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
#   - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
script:
  - go test -v -cover ./...
  - dep status
