version: '3'
services:
  database:
    image: "postgres:9.6.2"
    environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-developer}
        - POSTGRES_USER=${POSTGRES_USER:-developer}
        - POSTGRES_DB=${POSTGRES_DB:-worrywort}
        - PGDATA=${PGDATA:-/var/lib/postgresql/data/pgdata}
    privileged: true
    volumes:
      - worrywort_db:/var/lib/postgresql/data
  redis:
    image: 'redis:latest'
    restart: on-failure
    volumes:
        - worrywort_redis:/data
  worrywortd:
    image: worrywort-server:dev
    command: /bin/bash
    user: developer
    stdin_open: true
    tty: true
    depends_on:
      - database
      - redis
    working_dir: /go/src/github.com/jmichalicek/worrywort-server-go
    # command: /home/developer/docker_entrypoints/dev_entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: ${POSTGRES_DB:-worrywort}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-developer}
      DATABASE_USER: ${POSTGRES_USER:-developer}
      REDIS_HOST: redis
      PGPASSWORD: ${POSTGRES_PASSWORD:-developer}
      PGUSER: developer
      PGDATABASE: worrywort
      PGHOST: database
    ports:
      - "8080:8080"  # May muck with port.  I do not really care, it was just on 8080 from initial sample I used as starting point.
    restart: on-failure
    volumes:
      - .:/go/src/github.com/jmichalicek/worrywort-server-go/
      - ~/.gitconfig:/home/developer/.gitconfig:ro
      - ~/.git-hooks}:/home/developer/.git-hooks:ro
      - ~/.ssh:/home/developer/.ssh:ro
volumes:
  worrywort_db:
  worrywort_redis:
