version: '3'
services:
  database:
    image: "postgres:9.6.2"
    environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-developer}
        - POSTGRES_USER=${POSTGRES_USER:-developer}
        - POSTGRES_DB=${POSTGRES_DB:-worrywort}
        - PGDATA=${PGDATA:-/var/lib/postgresql/data/pgdata}
    privileged: true
    volumes:
      - worrywort_db:/var/lib/postgresql/data
  redis:
    image: 'redis:latest'
    restart: on-failure
    volumes:
        - worrywort_redis:/data
  worrywortd:
    image: worrywort-server:dev
    command: /bin/bash
    stdin_open: true
    tty: true
    depends_on:
      - database
      - redis
      # - hydra
    working_dir: /go/src/github.com/jmichalicek/worrywort-server-go
    # command: /home/developer/docker_entrypoints/dev_entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: ${POSTGRES_DB:-worrywort}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-developer}
      DATABASE_USER: ${POSTGRES_USER:-developer}
      REDIS_HOST: redis
      PGPASSWORD: ${POSTGRES_PASSWORD:-developer}
    ports:
      - "8080:8080"  # May muck with port.  I do not really care, it was just on 8080 from initial sample I used as starting point.
    restart: on-failure
    volumes:
      - .:/go/src/github.com/jmichalicek/worrywort-server-go/
      - ~/.gitconfig:/home/developer/.gitconfig:ro
      - ~/.git-hooks}:/home/developer/.git-hooks:ro
      - ~/.ssh:/home/developer/.ssh:ro
  # hydra:
  # Hydra may return, but removing for now for simplicity
  #   # Basing this on https://ory.gitbooks.io/hydra/content/install.html#install-and-run-ory-hydra
  #   image: oryd/hydra:v0.11.6
  #   depends_on:
  #     - database
  #   ports:
  #     # will figure out if I really need to do this.
  #     - "9000:4444"
  #   environment:
  #     SYSTEM_SECRET: ${HYDRA_SYSTEM_SECRET:-asecretwhichmustbeatleast32characterslongsomakeitlong}
  #     DATABASE_URL: postgres://developer:developer@database:5432/hydra?sslmode=disable
  #     ISSUER: https://localhost:9000
  #     # Not sure this is needed for what we are doing, but if consent app is needed
  #     # a simple nodejs for demo with Dockerfile is at https://github.com/ory/hydra-consent-app-express
  #     # and a sample Golang one, which would probably need to have similar code implemented by worrywort maybe
  #     # is at https://github.com/ory/hydra-consent-app-go
  #     CONSENT_URL: http://localhost:9020/consent
  #     FORCE_ROOT_CLIENT_CREDENTIALS: admin:demo-password
volumes:
  worrywort_db:
  worrywort_redis:
